# Application name
spring.application.name=payment-service

# Port where Payment Service runs - different from Order Service
server.port=8087
# PostgreSQL for idempotency
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Kafka Consumer settings - Payment Service RECEIVES events from Kafka
# bootstrap-servers = address of Kafka broker running in Docker
spring.kafka.bootstrap-servers=localhost:9092

# group-id = identifies which service is consuming
# all instances of Payment Service share this group
# Kafka divides messages between them automatically
spring.kafka.consumer.group-id=payment-group

# earliest = start reading from very first message in topic
# so Payment Service reads all messages it missed when it was down
spring.kafka.consumer.auto-offset-reset=earliest

# key-deserializer = converts bytes back to String when receiving message key
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# value-deserializer = we use StringDeserializer because we receive raw JSON string
# then manually convert to OrderEvent using ObjectMapper in PaymentConsumer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Kafka Producer needed for RetryableTopic to publish to retry topics
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Actuator for health checks zero downtime
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always