# Application name
spring.application.name=order-service

# Port where Order Service runs
server.port=8089

# PostgreSQL connection - connecting to Docker PostgreSQL container
# localhost = same machine, 5432 = PostgreSQL default port, orderdb = database name
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=admin
spring.datasource.password=admin

# JPA settings
# update = automatically creates/updates tables when app starts
spring.jpa.hibernate.ddl-auto=update
# show-sql = prints every SQL query in console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Producer settings - Order Service SENDS events to Kafka
# bootstrap-servers = address of Kafka broker running in Docker
spring.kafka.bootstrap-servers=localhost:9092

# key-serializer = converts message key (String) to bytes before sending to Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# value-serializer = converts Java object (OrderEvent) to JSON bytes before sending to Kafka
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# false = do not add Java class name in message headers
# so Payment/Inventory/Notification Service can deserialize without knowing Order Service class
spring.kafka.producer.properties.spring.json.add.type.headers=false